language: c

compiler:
  - gcc

matrix:
  include:
    - compiler: gcc
      env: CONFIGURE_OPTION='--enable-debug' COVERALLS=yes

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq automake pkg-config build-essential libtool automake autoconf m4 gnulib
  - sudo apt-get install -qq check libpcre3 libpcre3-dev libjemalloc-dev libjemalloc1
  - sudo apt-get install -qq graphviz-dev graphviz 
  - if [ x$COVERALLS == xyes ]; then sudo pip install cpp-coveralls --use-mirror; fi

script:
  - ./autogen.sh
  - ./configure $CONFIGURE_OPTION
  - make
  - make check

after_success:
  - if [ x$COVERALLS == xyes ]; then coveralls ; fi

cache:
  apt: true
