language: c
compiler:
  #  - clang
  - gcc
# for debian
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq automake pkg-config build-essential libtool automake autoconf m4 gnulib
  - sudo apt-get install -qq check libpcre3 libpcre3-dev libjemalloc-dev libjemalloc1
  - sudo apt-get install -qq graphviz-dev graphviz 
before_script:
  #  - aclocal
  #  - autoconf
  #  - automake --add-missing --foreign
  #  - autoreconf -i -I/usr/share/gnulib/m4 && ./configure && make
  - ./autogen.sh
  - ./configure && make
script:
  - make check
cache:
  apt: true
