language: c
compiler:
  - clang
  - gcc
# for debian
install:
  - sudo apt-get install check libpcre3 libpcre3-dev libjemalloc-dev libjemalloc1
before_script:
  - ./autogen.sh
  - ./configure && make
script:
  - make check
cache:
  apt: true
